trigger:
  branches:
    include:
    - 'master'
    - 'release/*'
    - 'internal/release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

phases:
  - template: .vsts-pipelines/templates/default-build.yml
    parameters:
      agentOs: Windows
