trigger:
  branches:
    include:
    - 'master'
    - 'release/*'
    - 'internal/release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

phases:
  - template: .vsts-pipelines/templates/default-build.yml
    parameters:
      agentOs: Windows
